### ISSUE TITLE
Error in sensor.py

### ISSUE THREAD

**Issue by venbea** [stamparm/tsusen#2]
Hello:

I tried to run tsusen but i have this error:

 **python tsusen.py
tsusen #v0.3.3

Traceback (most recent call last):
  File "tsusen.py", line 54, in <module>
    main()
  File "tsusen.py", line 39, in main
    init_sensor()
  File "/root/tsusen-master/core/sensor.py", line 192, in init_sensor
    items = re.findall(regex, subprocess.check_output(cmd))
AttributeError: 'module' object has no attribute 'check_output'**

mi python version = 2.6.6

Regards

**Comment by stamparm** [comment]
@venbea because it is new in Python 2.7 and you've tried to use Python 2.6. My mistake is that I haven't noticed this before. Please update to the latest revision and retry it again (you can try with Python 2.6 again)
