### ISSUE TITLE
Possibly wrong graph-statistics

### ISSUE THREAD

**Issue by MikhailKasimov** [stamparm/tsusen#6]
Hello!

Possibly wrong graph-statistics. ```tsusen``` conf and setting parameters are by default, with no changes.

```tsusen``` version: 0.3.6

See ```UDP 67``` statistics:

- On graph: 1
- On ```Counter``` tab: 4

![tsusen_wrong_counters](https://user-images.githubusercontent.com/7167300/40078128-676d3c3e-588c-11e8-841a-aa4cbd71acdf.png)

**Comment by MikhailKasimov** [comment]
Another one

![tsusen_wrong_counters_1](https://user-images.githubusercontent.com/7167300/40078742-343ed6a4-588e-11e8-9a50-3c3d1950a696.png)

**Comment by stamparm** [comment]
Number of intruders (different src_ip), not number of intrusions

**Comment by MikhailKasimov** [comment]
A, ok. Sorry for confusing.
